#!/bin/bash

icon=""
network=`iw wlp2s0 link`
name=$($network | grep "SSID" | awk '{print $2}')

if [ $network == "Not Connected."]
then
	printf "%s %s" "$icon" "Not Connected"
else
	printf "%s %s" "$icon" "$name"
fi
